import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import kleur from 'kleur';
import type { ProfileName, QualityLevel } from '../types.js';

export interface InitCommandOptions {
  preset?: ProfileName;
  yes?: boolean;
  force?: boolean;
}

const PRESET_DESCRIPTIONS: Record<ProfileName, { name: string; description: string }> = {
  web: {
    name: 'Web — smart routing (recommended)',
    description:
      'Automatically picks the best format. Plain PNGs become JPG (much smaller). Transparent PNGs stay as PNG (transparency stays intact). Best general-purpose default.',
  },
  preserve: {
    name: 'Web — keep every original format',
    description:
      "Never converts formats. PNG stays PNG, JPG stays JPG. Just compresses. Pick this if your HTML/CSS already references the existing files and you don't want to rename them.",
  },
  modern: {
    name: 'Web — convert everything to modern formats',
    description:
      'Maximum size reduction by converting to WebP/AVIF. Looks great in modern browsers, but you need to handle older browsers yourself.',
  },
  blog: {
    name: 'Blog (photo-first)',
    description:
      "Higher-quality JPEGs for photographs. Good when image quality matters more than the last few KB of savings.",
  },
  graphic: {
    name: 'UI / icons / logos',
    description:
      "Keeps PNG format, applies palette compression. Best for graphics with sharp edges (logos, screenshots, UI mockups) where JPG's blurry artifacts would look bad.",
  },
  archive: {
    name: 'Archive (highest quality)',
    description:
      'Larger files but pristine quality. Keeps EXIF metadata, uses lossless WebP, no PNG palette compression. Pick this if quality is more important than file size.',
  },
};

const QUALITY_DESCRIPTIONS: Record<QualityLevel, string> = {
  light: 'Quality first — only ~20-40% smaller files, near-zero loss',
  balanced: "Balanced — ~50-70% smaller, you can't tell the difference (recommended)",
  aggressive: 'Smaller — ~70-85% smaller, slight loss visible up close',
  extreme: 'Smallest — over 85% smaller, clearly lossy (use for thumbnails, avatars)',
};

export async function runInitCommand(
  options: InitCommandOptions,
): Promise<void> {
  const target = path.resolve('imgopt.config.js');

  if (existsSync(target) && !options.force) {
    process.stderr.write(
      kleur.red('✗') +
        ` imgopt.config.js already exists in ${process.cwd()}\n` +
        '  Use --force to overwrite.\n',
    );
    process.exit(1);
  }

  let preset: ProfileName = options.preset ?? 'web';
  let quality: QualityLevel = 'balanced';
  let outputDir = './optimized';

  // Interactive only when no preset and no --yes.
  if (!options.yes && !options.preset) {
    const { select, input } = await import('@inquirer/prompts');

    const startMode = await select<'quick' | 'preset' | 'custom'>({
      message: 'How do you want to start?',
      default: 'custom',
      choices: [
        { name: 'Customize (each prompt has a default — Enter to accept)', value: 'custom' },
        { name: 'Quick start (use all defaults — web preset)', value: 'quick' },
        { name: 'Pick a preset (no further questions)', value: 'preset' },
      ],
    });

    if (startMode === 'quick') {
      preset = 'web';
    } else {
      preset = await select<ProfileName>({
        message: 'What kind of images do you mainly work with?',
        default: 'web',
        choices: (Object.keys(PRESET_DESCRIPTIONS) as ProfileName[]).map(
          (k) => ({
            name: PRESET_DESCRIPTIONS[k].name,
            value: k,
            description: PRESET_DESCRIPTIONS[k].description,
          }),
        ),
      });

      if (startMode === 'custom') {
        outputDir = await input({
          message: 'Where should compressed files go?',
          default: './optimized',
        });

        quality = await select<QualityLevel>({
          message: 'How much should we compress?',
          default: 'balanced',
          choices: (Object.keys(QUALITY_DESCRIPTIONS) as QualityLevel[]).map(
            (k) => ({
              name: `${k}  —  ${QUALITY_DESCRIPTIONS[k]}`,
              value: k,
            }),
          ),
        });
      }
    }
  }

  const content = renderConfigTemplate({ preset, quality, outputDir });
  await writeFile(target, content, 'utf8');

  process.stdout.write(
    kleur.green('✓') +
      ` Created ${path.relative(process.cwd(), target)} (${preset} preset)\n` +
      kleur.dim('  Next: optimize <input> [--profile ' + preset + ']\n'),
  );
}

function renderConfigTemplate(opts: {
  preset: ProfileName;
  quality: QualityLevel;
  outputDir: string;
}): string {
  return `// imgopt.config.js — image-optimize per-project config
// Generated by \`optimize init --preset ${opts.preset}\`. Edit freely.

/** @type {import('image-optimize').UserConfig} */
export default {
  // How to handle each format:
  //   web      — automatic: opaque PNG → JPG, transparent PNG kept as PNG
  //   preserve — never converts, just compresses
  //   modern   — converts everything to WebP/AVIF
  //   blog     — like 'web' but with higher-quality JPEGs
  //   graphic  — keeps PNG (good for logos, icons, UI mockups)
  //   archive  — highest quality, larger files
  profile: '${opts.preset}',

  // How aggressive the compression should be:
  //   light       ~20-40%  smaller, near-zero quality loss
  //   balanced    ~50-70%  smaller, hard to tell the difference (recommended)
  //   aggressive  ~70-85%  smaller, slight loss visible up close
  //   extreme     >85%     smaller, clearly lossy (thumbnails, avatars)
  quality: '${opts.quality}',

  output: {
    // Compressed files go here
    dir: '${opts.outputDir}',

    // Filename template — placeholders: {name} {ext} {hash} {date} {w} {h}
    naming: '{name}.{ext}',

    // mirrorStructure: true
    //   When on:  input/a/b/c.png → output/a/b/c.jpg (keeps subfolder layout)
    //   When off (default): all files flattened into output/ root

    // slug: true
    //   When on: "Hello World.PNG" becomes "hello-world.jpg"
    //   Useful for assets going to URLs.
  },

  // Strip EXIF metadata (capture date, camera, GPS location).
  // ON for public web assets (privacy + saves a few KB).
  // OFF for personal archives where you want to keep that info.
  stripExif: true,

  // If compression saves less than this, skip the file and keep the original.
  // Reason: re-encoding lossy formats (JPG, WebP) repeatedly loses quality each
  // time. Not worth it for tiny savings.
  skipIfSmallerThan: '5%',


  // ─── advanced (uncomment to enable) ──────────────────────────────────────

  // Apply different rules to specific paths
  // rules: [
  //   { match: 'src/hero/**',   profile: 'blog' },
  //   { match: 'src/icons/**',  profile: 'graphic' },
  //   { match: 'src/photos/**', quality: 'aggressive' },
  // ],

  // Fine-tune PNG transparency handling (only when profile === 'web')
  // pngRoute: {
  //   convert: 'auto',
  //     // 'auto'     — decide based on transparency
  //     // 'jpg'      — always convert (will fill transparent areas with a colour!)
  //     // 'webp'     — always convert to WebP
  //     // 'preserve' — always keep as PNG
  //
  //   transparencyThreshold: 0.01,
  //     // <1% transparent pixels counts as "almost opaque"
  //     // (catches anti-aliased edges on screenshots)
  //
  //   routing: {
  //     opaque: 'jpg',           // where opaque PNGs go
  //     transparent: 'preserve', // where transparent PNGs go ('preserve' or 'webp')
  //   },
  //
  //   // flattenWith: '#ffffff',
  //     // background colour when flattening (rarely needed)
  // },

  // Animated GIF handling: 'webp' (smaller, animated) or 'preserve' (keep GIF)
  // gifRoute: { animated: 'webp' },

  // iPhone HEIC handling: 'jpg' / 'webp' / 'avif'
  // heicRoute: { convert: 'jpg' },

  // Custom filename transformer (overrides the slug setting above)
  // output: {
  //   transformName: (name) =>
  //     name.toLowerCase().replace(/\\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
  // },
};
`;
}
